@startuml
[*] --> Creada : Iniciar Acción (en Contexto)

Creada --> Ejecutada : Ejecutar Acción (por Actor)

Ejecutada --> EnValidacion : Observar Acción (por Espectador)

EnValidacion --> AuraIncrementada : Voto Positivo [Espectador != Actor] / sumarAura()
EnValidacion --> AuraReducida : Voto Negativo [Espectador != Actor] / restarAura()

AuraIncrementada --> [*]
AuraReducida --> [*]
@startuml
